config/routes.rb
Rails.application.routes.draw do
  get "static_pages/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if params[:query]
      service = PexelApiService.new(params[:query])
      service.call
      @photos = service.photos unless service.photos.nil?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Pexels Api" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Odin Pexels Api">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div style="width 100%; text-align: center;">
  <a href="https://www.pexels.com">
    <img src="https://images.pexels.com/lib/api/pexels.png" style="width: 300px;" />
  </a>
    <div style="margin: 10px auto; width: 50%; display: flex; flex-direction: column; align-items: center;">

      <%= form_with url: static_pages_home_path, method: :get do |form| %>

        <%= form.text_field :query %>
        <%= form.submit "Search images" %>

      <% end %>
      
    </div>

    <div style="margin: 50px auto; width:85%;">

      <% if @photos %>
        <h2>Images</h2>

        <div style="padding: 10px; border-radius: 10px; display:flex; flex-wrap: wrap; gap: 10px; width:100%; border: 2px solid gray;">
          <% @photos.each do |photo| %>

            <div style=" display: flex; flex-direction: column; align-items: start;">
              <%= image_tag(photo[:src]) %>
            </div>

          <% end %>
        </div>

      <% end %>
    </div>
</div>